In [1]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [1]:
# download data from kaggle
import kagglehub
path = kagglehub.dataset_download("colormap/spambase")

In [16]:
# copy downlaoded file
import shutil
shutil.copytree(path, "/home/anurag/Documents/github/medicaps/Sem06/machine-learning/03-spam-not-spam/datasets")

FileExistsError: [Errno 17] File exists: '/home/anurag/Documents/github/medicaps/Sem06/machine-learning/03-spam-not-spam/datasets'

In [17]:
# load dataset

# df = pd.read_csv(f"{path}/spambase.csv", encoding='latin-1')
df = pd.read_csv("datasets/spambase.csv", encoding='latin-1')

# check dataset
df.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  spam  
0                       278     1  
1                      1028     1  
2                      2259     1  
3                       191     1  
4                       191     1  

[5 rows x 58 columns]

In [18]:
X = df.iloc[:, :-1].values # all columns except the last one
Y = df.iloc[:, -1].values # only the last column

In [19]:
X

array([[0.000e+00, 6.400e-01, 6.400e-01, ..., 3.756e+00, 6.100e+01,
        2.780e+02],
       [2.100e-01, 2.800e-01, 5.000e-01, ..., 5.114e+00, 1.010e+02,
        1.028e+03],
       [6.000e-02, 0.000e+00, 7.100e-01, ..., 9.821e+00, 4.850e+02,
        2.259e+03],
       ...,
       [3.000e-01, 0.000e+00, 3.000e-01, ..., 1.404e+00, 6.000e+00,
        1.180e+02],
       [9.600e-01, 0.000e+00, 0.000e+00, ..., 1.147e+00, 5.000e+00,
        7.800e+01],
       [0.000e+00, 0.000e+00, 6.500e-01, ..., 1.250e+00, 5.000e+00,
        4.000e+01]])

In [20]:
Y

array([1, 1, 1, ..., 0, 0, 0])

In [21]:
# split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=12)

In [22]:
X_train

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 3.168e+00, 3.600e+01,
        3.010e+02],
       [1.900e-01, 1.900e-01, 2.900e-01, ..., 4.320e+00, 4.900e+01,
        8.770e+02],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.333e+00, 4.000e+00,
        2.400e+01],
       ...,
       [0.000e+00, 0.000e+00, 3.800e-01, ..., 2.953e+00, 3.400e+01,
        1.270e+02],
       [0.000e+00, 0.000e+00, 2.600e-01, ..., 1.635e+00, 6.000e+00,
        1.390e+02],
       [0.000e+00, 1.900e-01, 3.900e-01, ..., 1.357e+00, 1.900e+01,
        1.480e+02]])

In [23]:
X_test
# Y_train
# Y_test

array([[5.900e-01, 4.400e-01, 2.900e-01, ..., 7.300e+00, 7.630e+02,
        2.453e+03],
       [0.000e+00, 0.000e+00, 2.000e-01, ..., 2.224e+00, 1.900e+01,
        5.740e+02],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 3.100e+00, 1.100e+01,
        3.100e+01],
       ...,
       [0.000e+00, 1.030e+00, 0.000e+00, ..., 1.447e+00, 4.000e+00,
        5.500e+01],
       [0.000e+00, 0.000e+00, 1.500e+00, ..., 1.833e+00, 8.000e+00,
        2.200e+01],
       [0.000e+00, 0.000e+00, 1.230e+00, ..., 1.736e+00, 1.000e+01,
        6.600e+01]])

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train

array([[-0.35617595, -0.16348669, -0.56550534, ..., -0.06625794,
        -0.08506708,  0.03486824],
       [ 0.29867081, -0.00896792,  0.01969116, ..., -0.0318221 ,
        -0.02308516,  1.06875569],
       [-0.35617595, -0.16348669, -0.56550534, ..., -0.12111016,
        -0.23763796, -0.46233111],
       ...,
       [-0.35617595, -0.16348669,  0.20130387, ..., -0.07268476,
        -0.09460276, -0.27745193],
       [-0.35617595, -0.16348669, -0.04084641, ..., -0.11208271,
        -0.22810228, -0.25591261],
       [-0.35617595, -0.00896792,  0.22148306, ..., -0.12039275,
        -0.16612036, -0.23975811]])

In [26]:
X_test

array([[ 1.67729558,  0.19434625,  0.01969116, ...,  0.05725672,
         3.38115264,  3.89758664],
       [-0.35617595, -0.16348669, -0.16192155, ..., -0.09447619,
        -0.16612036,  0.52488781],
       [-0.35617595, -0.16348669, -0.56550534, ..., -0.06829061,
        -0.20426308, -0.4497665 ],
       ...,
       [-0.35617595,  0.67416769, -0.56550534, ..., -0.11770245,
        -0.23763796, -0.40668786],
       [-0.35617595, -0.16348669,  2.46137311, ..., -0.10616405,
        -0.2185666 , -0.46592099],
       [-0.35617595, -0.16348669,  1.91653499, ..., -0.1090636 ,
        -0.20903092, -0.38694348]])

In [33]:
def sigmoid(z): 
    return 1/(1+np.exp(-z))

print(sigmoid(np.array([-2, 1, 3])))

[0.11920292 0.73105858 0.95257413]


In [36]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [37]:
Y_pred = model.predict(X_test)

In [40]:
accuracy = accuracy_score(Y_test, Y_pred)

0.9315960912052117

### Model Accuracy

In [41]:
accuracy

0.9315960912052117

### Confusion matrix

In [42]:
confusion_matrix(Y_test, Y_pred)

array([[557,  21],
       [ 42, 301]])

### Classification Report

In [43]:
classification_report(Y_test, Y_pred)

'              precision    recall  f1-score   support\n\n           0       0.93      0.96      0.95       578\n           1       0.93      0.88      0.91       343\n\n    accuracy                           0.93       921\n   macro avg       0.93      0.92      0.93       921\nweighted avg       0.93      0.93      0.93       921\n'

## <b>Visualizing Decision Boundary<b>

In [44]:
def plot_decision_boundary(X, Y, model):
    x_min, x_max = X[:, 0].min() -1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() -1, X[:, 0].max() + 1
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100), np.linspace(y_min, y_max, 100))

    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    plt.coutourf(xx, yy, Z, aplha=0.3)

In [45]:
X_vis = X_train[:, :2]
model_vis = LogisticRegression()
model_vis.fit(X_vis, Y_train)

LogisticRegression()

In [47]:
plot_decision_boundary(X_vis, Y_train, model_vis)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed